# Generated by Django 2.2 on 2019-04-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190408_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-created_at',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
