# Generated by Django 2.2 on 2019-04-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-name',)},
        ),
    ]
