# Generated by Django 2.2 on 2019-05-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20190419_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='gallary_img/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='gallary_img/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='gallary_img/%Y/%m/%d')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='gallary_img/%Y/%m/%d')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='gallary_img/%Y/%m/%d')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='gallary_img/%Y/%m/%d')),
            ],
        ),
    ]
