# Generated by Django 2.2 on 2019-04-08 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=233, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+233'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
